leader_control_node:
  ros__parameters:
    control_frequency: 50.0
    leader_id: 1
    command_timeout: 1.0
    yaw_debug_enabled: true
    yaw_debug_interval: 1.0
    target_debug_enabled: true
    target_debug_interval: 1.0
    cpf_max_speed: 0.6


    # Rectangular world fence in ROS ENU frame.
    fence_enabled: true
    fence_world_x_min: -1.7
    fence_world_x_max: 1.7
    fence_world_y_min: -1.5
    fence_world_y_max: 1.5
    fence_height_min: 0.0
    fence_height_max: 1.4
    fence_brake_distance_m: 0.35

    vehicle_names:
      - MAV1
      - MAV2
      - MAV3

    vehicle_system_ids:
      - 1
      - 2
      - 3
